const enUS = {
	privateVehicle: 'private vehicle',
	privateTitle: 'mobile car connect key(MCCK)',
	pleaseLogIn: 'please login',
	InstInstall: 'Inst Install',
	MoreSettings: 'More Settings',
	battery: 'battery',
	btStatus: 'btStatus',
	connected: 'connected',
	disConn: 'disConn',
	btPairing: 'btPairing',
	unpaired: 'unpaired',
	mcckDeviceBattery: 'mcckDeviceBattery',
	mcckBtConnManual: 'mcckBtConnManual',
	mcckBtPairingInductive: 'mcckBtPairingInductive',
	InductiveLock: 'Inductive Lock',
	On: 'Auto lock/unlock without waiting or checking',
	Off: 'Manual operation required: Go to My Phone Car Key to lock/unlock',
	MyLocation: 'My Loc',
	UnlockSensitivity: 'Unlock Sens',
	LockSensitivity: 'Lock Sens',
	Rule: 'Rule',
	MyLocationdes: 'Bluetooth signal: Lower = stronger',
	UnlockSensitivitydes: 'Unlock when signal < this value',
	LockSensitivitydes: 'Lock when signal > this value',
	Ruledes: '"My Loc": Value updates in real time as phone moves',
	Tip: "Tip:Adjust lock/unlock values in DIY settings if default doesn fit",
	SensVal: 'Sens Val',
	FactoryReset: 'Factory Reset',
	Unlock: 'Unlock ',
	Lock: 'Lock ',
	Driving: 'Frequent Lock/Unlock While Driving ',
	Custom:'Comfort Entry Custom',
	Diy1:'Unlock too far: Slide "Lock" icon to lower value. Too close: Slide to raise it.',
	Diy2:'Lock too far: Slide "Lock" icon to lower value. Too close: Slide to raise it.',
	Diy3:'Frequent lock/unlock while driving? Raise value. Lock value updates sync, sensitivity reduces.',
	MyCarKey:'My Car Key',
	MoreKeys:'More Keys'
};
const zhCN = {
	privateVehicle: '私家车',
	privateTitle: '智信通手机汽车互联钥匙',
	pleaseLogIn: '请登录',
	InstInstall: '安装说明',
	MoreSettings: '更多设置',
	battery: '电量',
	btStatus: '蓝牙状态',
	connected: '已连接',
	disConn: '未连接',
	btPairing: '蓝牙配对',
	unpaired: '未配对',
	mcckDeviceBattery: 'MCCK 设备当前电量',
	mcckBtConnManual: 'MCCK 蓝牙连接（支持手动）',
	mcckBtPairingInductive: 'MCCK 蓝牙配对（感应生效）',
	InductiveLock: '感应开关锁',
	On: '开启：实现开门不罚站 关门不回头，无感自动开关锁。',
	Off: '关闭：需手动操作： 在「我的手机汽车钥匙功能」区域-完成开关门操作。',
	MyLocation: '我的位置',
	UnlockSensitivity: '开锁敏感值',
	LockSensitivity: '关锁敏感值',
	Rule: '变化规则',
	MyLocationdes: '手机与硬件设备的蓝牙信号值，数值越小信号越强',
	Ruledes: '我的位置,该数值随手机移动实时变动',
	UnlockSensitivitydes: '信号值低于此值，车辆感应开锁',
	LockSensitivitydes: '信号值高于此值，车辆感应关锁',
	Tip: "温馨提示：默认设置若不合预期（开关锁位置/距离），请在个下方性化DIY 处调整开关锁值",
	SensVal: '敏感值',
	FactoryReset: '恢复出厂设置',
	Unlock: '开锁',
	Lock: '关锁',
	Driving: '开车期间频繁开关锁',
	Custom:'舒适进入个性化',
	Diy1:'如开锁距离过远，则滑动"锁"图标调小数值，如开锁距离过近，则滑动"锁"图标调大数值。',
	Diy2:'如关锁距离过远，则滑动"锁"图标调小数值，如关锁距离过近，则滑动"锁"图标调大数值。',
	Diy3:'如开车期间频繁开关锁，建议调大数值～调整后关锁数值会同步更新，关门敏感度会降低。',
	MyCarKey:'我的手机汽车钥匙功能',
	MoreKeys:'更多钥匙功能'
	



};
export const bilingualData = {
	en_US: enUS,
	zh_CN: zhCN
}